config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: %i[new create]
    resources :ingredients, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true

  # before_destroy :check
  # def check
  #   return self.ingredients.still_there.empty?
  # end
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient_id, uniqueness: true
  validates :ingredient_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show, :destroy]

  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail, notice: 'Cocktail was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @cocktail.destroy
    redirect_to cocktail_url, notice: 'Cocktail was successfully destroyed.'
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :doses, :ingredients)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<ul>
  <li>
<% @cocktails.each do |cocktail| %>
      <tr>
        <td>
          <%= cocktail.name %>
        </td>
        <td>
          <%= link_to 'Show', cocktail_path(cocktail) %>
        </td>
      </tr>
    <% end %>
  </li>
</ul>

app/views/cocktails/new.html.erb
<%= form_for([@cocktail, @doses, @ingredients]) do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %>
   <%= f.label :doses %>
   <%= f.text_field :doses %>
   <%= f.label :ingredients %>
   <%= f.text_field :ingredients %>
   <%= f.submit %>
 <% end %>

app/views/cocktails/show.html.erb
<p>
  <strong><%= @cocktail.name %></strong>
</p>
<p>

</p>

app/views/doses/index.html.erb
<h1>Doses</h1>

<ul>
  <li>
<% @doses.each do |cocktail| %>
      <tr>
        <td>
          <%= dose.name %>
        </td>
        <td>
          <%= link_to 'Show', dose_path(dose) %>
        </td>
      </tr>
    <% end %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>